# -*- coding: utf-8 -*-
"""Compare text within 2 txt files to find differences.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rduHxVMTf18_feEQ5vlH2VU3LQ1crBTD
"""

from difflib import Differ

file1=open('/content/sample1.txt','r')
file2=open('/content/sample2.txt','r')

differ=Differ()

for line in differ.compare(file1.readlines(),file2.readlines()):
  print(line)

"""'-' line unique to sequence 1

'+' line unique to sequence 2

' ' line common to both sequences

'?' line not present in either input sequence
"""







