# -*- coding: utf-8 -*-
"""Download YouTube mp4 as mp3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aZsigo3qldOApRfRXMez7LQw3LnhaKTU
"""

#Don't run under normal circumstances
!pip uninstall pytube
!pip uninstall pytube3

!pip install pytube3
!pip install pytube moviepy
!pip install -U youtube-dl

#!pip install --upgrade pytube
#!pip install --upgrade pytube3

#Don't need to run
!pip install pytube

#Don't need to run
!pip install pytube@git+https://github.com/priyankaj1311/pytube.git@master_copy

from pytube import YouTube
from moviepy.editor import *

yt=YouTube(str(input('Enter url: \n')))

stream=yt.streams.get_highest_resolution()

import re
streams=stream.download()
name=re.split("/content/",streams)
name

video=VideoFileClip(str(name[1]))
audio=video.audio

audio.write_audiofile("王朝-空待.mp3")



"""---
#Basic Version
















"""

#More Basic Version

from pytube import YouTube
from moviepy.editor import *

yt=YouTube(str(input('Enter url: \n')))

stream=yt.streams.get_highest_resolution()

stream.download()

video=VideoFileClip('PRINCE OF TENNIS OP 2 DRIVING MY SELF.mp4')
audio=video.audio

audio.write_audiofile('Prince of Tennis OP2-Driving My Self.mp3')