# -*- coding: utf-8 -*-
"""Check_Password_Valid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k9ibPZ-9j7f3rgueN9KGjg1nJZ8d9jGb

Write a function to determine whether the password satisfies the following conditions:
1. Length is between 8-20 characters
2. At least 1 Capital letter
3. At least 1 Lower Case letter
4. At least 1 number
5. At least 1 special character
"""

import re

password=input("Please enter your password: ")

"""##Functions that are used to check each condition"""

def check_length(password):
  length=False
  password_length=len(password)
  if password_length>=8 and password_length<=20:
    length=True
  return length

def check_capital(password):
  capital=False
  for char in password:
    if char.isupper():
      capital=True
  return capital

def check_lower(password):
  lower=False
  for char in password:
    if char.islower():
      lower=True
  return lower

def check_number(password):
  num=False
  for char in password:
    if char.isdigit():
      num=True
  return num

pattern=r'[!@#$%^&*(),.?":{}|<>]'

def check_special(password):
  special=False
  if re.search(pattern, password):
    special=True
  return special

"""##Check Password and output whether it passed the test
If it didn't, then it will also output the conditions it fails to meet
"""

if check_capital(password) and check_length(password) and check_lower(password) and check_number(password) and check_special(password):
  print("The password is valid and contains all the elements required")
else:
  false_conditions=[]

  if not check_capital(password):
    false_conditions.append("No capitalization\n")
  if not check_length(password):
    false_conditions.append("Not between 8 and 20 characters\n")
  if not check_lower(password):
    false_conditions.append("No lower case\n")
  if not check_number(password):
    false_conditions.append("No number\n")
  if not check_special(password):
    false_conditions.append("No special character\n")
print("The password failed to satisfy the requirements:")
print(false_conditions)



