# -*- coding: utf-8 -*-
"""num_of_occurrence_in_text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UT7ZW_CJcM58jEvPXVog5zR470ixDFCQ
"""

#reads a txt file
text=open('/content/sample1.txt').read()
text

#open the txt file to read
#text=open('/content/sample1.txt').read()

#set an empty dictionary
words={}
#for each line in text, split by line
for line in text.splitlines():

  #split each line by word using .split()
  line=line.split()
  #for each word of the current line of text
  for word in line:
    if word not in words: #if the word doesn't already exist
      words[word]=1 #Then it's the first occurrence
    else:
      words[word]+=1 #add 1 to the dictionary where there's the instance of that word

words

#sort by number of occurrence
sorted_words=sorted(words.items(),key=lambda x:x[1],reverse=True)
#Top 10 occurrence
sorted_words[:10]